approval_policy = "on-request"
model = "gpt-5.6-sol"
model_provider = "openai_http"
model_reasoning_effort = "medium"
personality = "pragmatic"
sandbox_mode = "danger-full-access"
service_tier = "default"


[desktop]
ambient-suggestions-enabled = true
appearanceDarkCodeThemeId = "everforest"
appearanceLightCodeThemeId = "rose-pine"
codeFontSize = 13
composerEnterBehavior = "cmdIfMultiline"
conversationDetailMode = "STEPS_COMMANDS"
defaultTerminalLocation = "right"
enabled-reasoning-efforts = [ "low", "medium", "high", "xhigh", "max", "ultra" ]
followUpQueueMode = "steer"
hotkey-window-projectless-default-enabled = true
keepRemoteControlAwakeWhilePluggedIn = true
mac-menu-bar-enabled = false
notifications-turn-mode = "unfocused"
preventSleepWhileRunning = true
sansFontSize = 13
selected-avatar-id = "rocky"
show-context-window-usage = true
show-ultra-in-model-picker-slider = true
useFontSmoothing = true
usePointerCursors = true

[desktop.appearanceDarkChromeTheme]
accent = "#a7c080"
contrast = 20
ink = "#d3c6aa"
opaqueWindows = false
surface = "#2d353b"

[desktop.appearanceDarkChromeTheme.fonts]
code = "Monaspace Argon Var, Monaspace Argon NF"
ui = "Monaspace Neon Var, PingFang SC"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#a7c080"
diffRemoved = "#e67e80"
skill = "#d699b6"

[desktop.appearanceLightChromeTheme]
accent = "#d7827e"
contrast = 45
ink = "#575279"
opaqueWindows = false
surface = "#faf4ed"

[desktop.appearanceLightChromeTheme.fonts]
code = "Monaspace Argon Var, Monaspace Argon NF"
ui = "Monaspace Neon Var, PingFang SC"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#56949f"
diffRemoved = "#797593"
skill = "#907aa9"

[desktop.open-in-target-preferences]
global = "systemDefault"

[features]
hooks = true
js_repl = false
memories = true
multi_agent = true
workspace_dependencies = true

[memories]
consolidation_model = "gpt-5.4-mini"
extract_model = "gpt-5.4-mini"
generate_memories = true
use_memories = true
